name: Auto-respond to new issues

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-comment on new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.issue;
            const body = `感谢你提交 issue！为帮助我们更快定位并复现问题/需求，请补充下列信息（如适用）：

- 策略名称 / 模块：
- 回测时间区间 / 历史数据范围：
- 复现步骤或示例（最好附上重现代码片段）：
- 期望行为与实际表现：

我会尽快阅读并回复。`;
            await github.rest.issues.createComment({ ...issue, body });
