name: Daily Haili backtest

on:
  schedule:
    - cron: '30 0 * * *'  # runs daily at 00:30 UTC
  workflow_dispatch:
    inputs:
      tickers:
        description: 'Space-separated tickers, e.g. "000001.SZ 600519.SH"'
        required: false
        default: '000001.SZ 600519.SH'

jobs:
  run-backtest:
    runs-on: ubuntu-latest
    env:
      # fallback used for scheduled runs when workflow_dispatch inputs are not present
      DEFAULT_TICKERS: '000001.SZ 600519.SH'
      TICKERS: ${{ github.event.inputs.tickers || '000001.SZ 600519.SH' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install akshare pandas numpy matplotlib

      - name: Run haili_backtest
        run: |
          echo "Running backtest for: $TICKERS"
          # pass the space-separated tickers as individual args to --tickers
          python haili_backtest.py --tickers $TICKERS

      - name: Upload CSV artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: haili-results
          path: |
            *_haili_detailed_*.csv
            candidates_haili_style.csv