name: Daily Haili Backtest

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间16:30 (UTC 08:30)
    - cron: '30 8 * * *'

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Haili Integrated Backtest CLI
        run: python -u scripts/integrated_backtest_cli.py

      - name: Generate Timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Generate backtest reports
        run: |
          TIMESTAMP=${{ env.TIMESTAMP }}
          # The new CLI already outputs to backtest_results directory
          # Generate reports if available
          python generate_backtest_report.py --input-dir backtest_results || echo "Report generation failed"

      - name: Commit Results to History Branch
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin results || true
          git checkout -B results origin/results || git checkout -b results
          mkdir -p results/${TIMESTAMP}
          # Copy all backtest_results content to the timestamped directory
          cp -r backtest_results/* results/${TIMESTAMP}/ || true
          git add results/
          git commit -m "Backtest results for ${TIMESTAMP}" || echo "No changes to commit"
          git push origin results

      - name: Upload Backtest Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results-${{ env.TIMESTAMP }}
          path: |
            results/${{ env.TIMESTAMP }}/
          if-no-files-found: ignore