name: Haili Backtest CI

on:
  push:
    branches: [ main ]
  schedule:
    # Daily at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-haili-backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy akshare
          fi

      - name: Run haili_backtest.py in CI mode
        env:
          CI_TICKERS: ${{ vars.CI_TICKERS || '000001.SZ' }}
        run: |
          python haili_backtest.py --ci-mode

      - name: Upload generated CSVs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: haili-backtest-results
          path: results/*.csv
          if-no-files-found: warn
