name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            python-version-dashed: "3-10"
          - python-version: "3.11"
            python-version-dashed: "3-11"
          - python-version: "3.12"
            python-version-dashed: "3-12"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          mkdir -p test-results
          pytest -q --junitxml=test-results/pytest.xml

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version-dashed }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            test-results/**
            .pytest_cache/**
          if-no-files-found: ignore
          overwrite: true
          retention-days: 7
